### ISSUE TITLE
SharedElementCallback只执行一次

### ISSUE THREAD

**Issue by zhuzhutai** [yellowcath/YcShareElement#1]
我用在自己的项目里
A进入B 动画执行 SharedElementCallback 执行
B finsh 返回A SharedElementCallback完全不执行了 
会跟什么有冲突吗

**Comment by yellowcath** [comment]
看看B里面有没有执行super.finishAfterTransition();
这个函数里面会把B的mEnterTransitionListener当做参数构造一个ExitTransitionCoordinator，然后才会有退出动画的回调

**Comment by zhuzhutai** [comment]
> 看看B里面有没有执行super.finishAfterTransition();
> 这个函数里面会把B的mEnterTransitionListener当做参数构造一个ExitTransitionCoordinator，然后才会有退出动画的回调

ContactsActivity --》DetailActivity
在你的demo里面这种简单跳转并没有使用这个方法啊

**Comment by yellowcath** [comment]
这个是默认会执行的，但是如果被覆盖了的话可能就没执行。
另外你可以通过在模拟器上断点进这个函数调试，找到具体是哪一步导致回调没有被调用的

**Comment by zhuzhutai** [comment]
> 这个是默认会执行的，但是如果被覆盖了的话可能就没执行。
> 另外你可以通过在模拟器上断点进这个函数调试，找到具体是哪一步导致回调没有被调用的

天啊 
supportFinishAfterTransition();这个方法必须手动调用才能激活setEnterSharedElementCallback(new SharedElementCallback() 虽然我没在你的demo里面找到哪里调用了
而且
setEnterSharedElementCallback这个方法有两个包名！！！！！！！！！要与之匹配才行...

**Comment by yellowcath** [comment]
看了下源码，这个是在onBackPressed()里面调用的，所以如果你是直接调的finish的话，确实没执行
