### ISSUE TITLE
没有androidx版本吗

### ISSUE THREAD

**Issue by glongdev** [yellowcath/YcShareElement#4]
androidx的项目不能扩展啊

**Comment by yellowcath** [comment]
这个和androidx没啥子关系，不冲突

**Comment by SharksLee** [comment]
> 这个和androidx没啥子关系，不冲突

肯定是有问题的，如果我项目用的是anroidx，里面的使用的support相关的东西都应用不到了

**Comment by yellowcath** [comment]
com.github.yellowcath:VideoProcessor:2.4.0
已经去掉了对android support library的依赖

**Comment by yellowcath** [comment]
implementation 'com.github.yellowcath:YcShareElement:1.3.2.x'
这个里面换成androidx了
